### ISSUE TITLE
modal.close() is throwing error "Expression has changed after it was checked"

### ISSUE THREAD

**Issue by mehtak** [dougludlow/ng2-bs3-modal#140]
I am creating a parent-child relationship to show ng2-bs3-modal. Parent component has a table. After collecting user inputs on Child modal dialog (ng3-bs3-modal component) I am closing the dialog and making an http get call to load table data. If I call modal.close() and then make the http call, the following error is displayed and http result is not returned. 

`error_handler.js:46 EXCEPTION: Error in ./ChildModal class ChildModal - inline template:11:12 caused by: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.`

Note: I am closing the modal using keyup.enter() event on 'Get Data' button. This error comes only with Keyboard interaction, not with mouse click on 'Get Data' button.

```javascript
keyPressFunction(event, value) {
    if (value === 'Enter') {
       this.getData(); //custom function to make http GET call.
      event.preventDefault();
      event.stopPropagation();
    }
  }

getData() {
    //do something to fetch data from HTTP get().
    modal.close();
    }
  }
```
If I comment out modal.close() then data loads fine, no error, but modal remains on screen.

Let me know if data is not sufficient.

**Comment by dougludlow** [comment]
Hmm... I'll have to see if I can replicate this issue.

**Comment by dougludlow** [comment]
@mehtak you might check out the comments on https://github.com/angular/angular/issues/6005 and see if any are helpful. Without a working demo, it's hard for me to replicate.

**Comment by renehamburger** [comment]
We are regularly running into this exception when an ng2-bs3-modal is opened. It happens if an element is focused that has an Angular2 blur-handler (e.g. an input with [ngModel]) and when a click then opens the the ng2-bs3-modal.

What happens is this:
- click event triggers first round of change detection
- any properties influenced by the blur event still have their initial value; `ngClassUntouched`, for example, is still `true`
- Angular saves this value
- ng2-bs3-modal shows the Bootstrap modal
- Bootstrap triggers a focus event on the modal in modal.js#108
- the blur event is triggered on the initial element
- the (getter) property `ngClassUntouched` is changed to `false`
- the second change detection is triggered
- the exception is thrown as this property has changed from `true` to `false` between these 2 rounds.

The easiest way to prevent this is to open the dialog 1 tick later with `setTimeout(() => this.modal.open())` in our code. Though it might make sense to do exactly that in `ModalInstance::show()` to prevent this from happening to others.

**Comment by renehamburger** [comment]
@dougludlow: Actually, I think this issue may be quite specific to our setup. The reason ng2-bs-modal is shown _within_ a change detection cycle in our case is that we've call `this.modal.open()` from within `ngOnChanges()`. So probably not something that you'll need to worry about. But this issue could still be helpful to others encountering this exception when using this module.
