### ISSUE TITLE
Issue with cssClass

### ISSUE THREAD

**Issue by mrj365** [dougludlow/ng2-bs3-modal#190]
I don't think the cssClass attribute is working on the ModalComponent. 

When I define:

`<modal #modalService [cssClass]="sm-modal" [size]="lg">`

When the modal is opened, I see the following in the rendered html:

`<div class="modal-dialog NaN" ng-reflect-klass="modal-dialog" ng-reflect-ng-class="NaN">`

I have tried defining the css class sm-modal in styles.css and in the components css file and neither have worked for me. I still see "NaN.

**Comment by dougludlow** [comment]
What happens when you do `[cssClass]="'sm-modal'"` (surround with single quotes as well)?

**Comment by wartab** [comment]
[cssClass] is not a documented feature afaik. Nevertheless, NaN is the result of the calculation of `undefined - undefined`, because you are trying to subtract the variables `sm` and `modal` that most likely don't exist in your component.

I recommend not using [cssClass] at all. If you want the <modal> to have a class, just use the classical class HTML attribute.

**Comment by dougludlow** [comment]
@warrab, it's documented. The class is applied to the modal as opposed to the modal container.

**Comment by wartab** [comment]
Oh alright. I thought, for some reason, that this was an Angular feature and not of your package.

But my explanation of why this is giving NaN still holds.

**Comment by dougludlow** [comment]
@wartab yessir, it does. Thanks for the explanation!

**Comment by mrj365** [comment]
Ah, I didn't realized angular was evaluating that expression. adding single quotes did the trick. Thanks!
