### ISSUE TITLE
Modal Component support in Angular 2.0

### ISSUE THREAD

**Issue by ashfaque-rifaye** [dougludlow/ng2-bs3-modal#249]
We Have Angular 2.0 Project and we are trying to update this Modal component. When trying to update, there was a warning message (PFB the image) mentioning that we require a **"@angular/common@^6.0.0-rc.0" , "@angular/core@^6.0.0-rc."0  and "rxjs@^6.0.0"**. We might not be able to update the other packages, but this requires to be installed without affecting other packages. Any fixes for this?

![image](https://user-images.githubusercontent.com/33770527/46060528-4fe2b680-c181-11e8-8240-f0b562e33039.png)

**Comment by wartab** [comment]
Angular 2.0 is not maintained anymore, critical upates have been added to it and you shouldn't be staying on an old version in the first place. If you still feel like taking security risks, you can try and go back to the older releases of this package and install them instead of the up to date versions as well. This warning is a hint, not an error.
