### ISSUE TITLE
Missing peer dependency if compiling bootstrap with sass or less

### ISSUE THREAD

**Issue by iherbivore** [dougludlow/ng2-bs3-modal#28]
In my project I have boostrap-sass installed as a dev dependency. Is there way to install this since I don't have the pre-built bootstrap installed?

**Comment by dougludlow** [comment]
Hmm... from what I understand a missing peer dependency will throw a warning, but npm doesn't require that you fill that dependency. My npm fu isn't the greatest. I don't know of a way to tell npm that you can depend on one package or another package. That's why I listed it as a peerDependency.

**Comment by dougludlow** [comment]
From [npm Weekly, #5](http://blog.npmjs.org/post/110924823920/npm-weekly-5):

> We will also be changing the behavior of peerDependencies in npm@3. We won’t be automatically downloading the peer dependency anymore. Instead, we’ll warn you if the peer dependency isn’t already installed. This requires you to resolve peerDependency conflicts yourself, manually, but in the long run this should make it less likely that you’ll end up in a tricky spot with your packages’ dependencies.

**Comment by dougludlow** [comment]
npm's documentation on [peerDependencies](https://docs.npmjs.com/files/package.json#peerdependencies).

**Comment by samvloeberghs** [comment]
**If you really want to remove this warning; **basically you could just add bootstrap@3.3.6 as a (optional or dev ) dependency in your project. If you don't include it or whatever it will not impact your distributable, only the project size on your workstation.
```

npm install -S --save-dev bootstrap@3.3.6
npm install -O --save-optional bootstrap@3.3.6
```

**Comment by dougludlow** [comment]
I like that. Probably the best way to go.

**Comment by iherbivore** [comment]
Thanks, I should have realized that.

**Comment by maxfisher05** [comment]
I would like to use this with bootstrap4, the API hasn't changed for modal so this works out of the box: http://v4-alpha.getbootstrap.com/components/modal/

The only issue is the peerDependency.

using node v5.8.0 it actually fails the build.

npm ERR! peerinvalid The package bootstrap@4.0.0-alpha.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer ng2-bs3-modal@0.5.2 wants bootstrap@~3.3.x

Can't use the save-dev or optional suggestion above as it conflicts with the 4.0 version in regular dependencies.

Aside from the package name containing "bs3" any reason to not allow this on bootstrap 4?  change peerDependency to >3.3.x instead of ~3.3.x

Thanks!

**Comment by samvloeberghs** [comment]
@maxfisher05 : that would require a name change as the current name, like you say, references to bs3. Allowing it to use bs4 could be confusing. What if bootstrap suddenly decides they skip Bootstrap4 and go for Bootstrap5 ( e.g. PHP )? Than it would definitely be confusing.

I would suggest to clone and make your own version "ng2-bs4-modal" ( but whoami :) )

**Comment by dougludlow** [comment]
@maxfisher05, @samvloeberghs, that's probably the best way to go, I'd rather not support both versions in one project, the code could get messy. I'm open to helping facilitate creating a clone/new repo for ng2-ns4-modal.

**Comment by maxfisher05** [comment]
thanks doug, I created a fork for now: https://github.com/maxfisher05/ng2-bs4-modal

**Comment by dougludlow** [comment]
@maxfisher05 awesome! Let me know where you can use a hand.
