### ISSUE TITLE
onOpen eventemitter not triggered

### ISSUE THREAD

**Issue by hakalb** [dougludlow/ng2-bs3-modal#37]
I can not get onOpen() eventemitter to be triggered when modalcomponent.open() is triggered.
It's working with onDismiss().

**Comment by dougludlow** [comment]
@hakalb thanks for reporting this. I'll take a look.

**Comment by hakalb** [comment]
I solved it for now by using @ViewChild() and trigger modal open inside my component. The returned promise tells me when modal is fully opened. Works like a charm and is as good as onOpen().

**Comment by dougludlow** [comment]
Ha ha, brilliant. I'll still look into why it's not emitting.

**Comment by dougludlow** [comment]
@hakalb sorry it took me a while to look into this. Unfortunately I haven't been able to repro this issue. I added a test that checks that onOpen emits when the modal is opened. I've also updated my [demo](http://dougludlow.github.io/ng2-bs3-modal/) and it appears to update onOpen just fine. Let me know if you find otherwise, but I'm going to close this issue for now.
