### ISSUE TITLE
Out of date deps?

### ISSUE THREAD

**Issue by psibernetic** [dougludlow/ng2-bs3-modal#48]
├── UNMET PEER DEPENDENCY @angular/common@^2.0.0-rc.1
├── UNMET PEER DEPENDENCY @angular/compiler@^2.0.0-rc.1
├── UNMET PEER DEPENDENCY @angular/core@^2.0.0-rc.1
├── UNMET PEER DEPENDENCY @angular/platform-browser@^2.0.0-rc.1
├── UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@^2.0.0-rc.1
└── ng2-bs3-modal@0.6.0

I am running the latest angular2 packages.

**Comment by dougludlow** [comment]
@psibernetic what version of angular do you have installed? As of [rc.0](https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc0-2016-05-02), the angular team changed how angular2 was distributed on npm:

> All of the packages are now distributed under the `@angular` npm scope. This changes how Angular is installed via npm and how you import the code.

You can install rc.1 with:

```bash
npm install --save @angular/core @angular/compiler @angular/common @angular/platform-browser @angular/platform-browser-dynamic rxjs@5.0.0-beta.6 zone.js@0.6.12
```

And remove the old one like so:

```bash
npm uninstall --save angular2
```

Otherwise `ng2-bs3-bootstrap@0.5.x` still works with `angular2@2.0.0-beta.x`.

**Comment by psibernetic** [comment]
Thanks!
